# 예외를 잡는 방법

throw 문은 throw 문을 실행하는 메서드로 시작하여 main 메서드까지 호출 메서드로 이어지는 메서드 종료 체인을 시작합니다.

예외가 발생하면 프로그램 종료로 이어지는 일련의 예외가 중단된다.

예외를 포착하려면 `try-catch-finally`구조를 사용할 수 있다.

**Syntax**
```java
try {
    try-block
} 
catch(ExceptionClass1 e) {
    catch-block
}
catch(ExceptionClass2 e) {
    catch-block
}
finally {
    finally-block
}
```

- `try-block` : 다음 `catch`절의 제어 하에 실행될 일련의 명령문
- `catch-block` : `try-block`의 명령문이 해다 catch 절에 지정된 유형의 예외를 생성하는 경우 실행될 명령문
- `finally-block` : 항상 실행되는 일련의 명령문

**Semantics**
코드 조각에서 발생할 수 있는 하나 이상의 예외를 포착한다. 이러한 명령문 중 하나가 예외를 생성하는 경우 `try-block`명령문 실행이 중단된다. 이런 일이 발생하면 `catch`절은 작성된 순서대로 평가되고 생성된 예외가 지정된 클래스에 속하는 첫 번째 절에 해당하는 `catch`블록이 실행된다. 마지막으로 `finally` 명령문이 실행된다.