# 예외 전파 중단

예외를 생성하는 메서드에서 예외가 처리되지 않고 예외를 생성하는 메서드를 호출하는 메서드에서 처리된다. 그러면 예외가 더 이상 위쪽으로 전파되지 않는다. 따라서 예외를 발생시키도록 `throws`절을 선언할 필요가
없다.

```java
import java.io.*;

public class ExceptionPropagation2 {

    public static void main(String[] args) throws IOException {
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        System.out.println("Insert a number:");
        int c = Integer.parseInt(br.readLine());
        first(c);
    }

    private static void first(int a) {
        try {
            second(a);
        } catch (Exception e) {
            System.out.println("Exception handled in the first method.");
            System.out.println(e.getMessage());
        }
    }

    private static void second(int b) throws Exception {
        Exception propagate = new Exception("The value is too small.");
        if (b < 10)
            throw propagate;
        System.out.println("OK");
    }
}
```